(ns euler.clj (:use euler.clj))

;; Each new term in the Fibonacci sequence is generated by adding the
;; previous two terms. By starting with 1 and 2, the first 10 terms
;; will be:
;;
;; 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;;
;; Find the sum of all the even-valued terms in the sequence which do
;; not exceed four million.

(defn fib-generator [x]
  [(+ (first x) (second x)) (first x)])

(defn gen-fibonacci [upto]
  (take-while #(< %1 upto)
              (map first (iterate fib-generator [1 1]))))

(defn solve-problem002 []
  (apply + (filter even?
                   (gen-fibonacci 4000000))))
